package com.example.reservation.domain.guest;

public enum Language {
    ENGLISH, KOREAN, JAPANESE, CHINESE_SIMPLIFIED, CHINESE_TRADITIONAL, 
    SPANISH, FRENCH, GERMAN, ITALIAN, PORTUGUESE, RUSSIAN, ARABIC
}